### ISSUE TITLE
ルーム検索画面のリファクタリング

### ISSUE THREAD

**Issue by txxxxc** [lit-kansai/dj-system-ios#48]
### HomePageの名前変更

HomePageからSearchRoomPageに名前を変更してください！！

### APIとの通信周りをAPIClientに書き換える

APIの通信周りをAPIClientを使って書き換えてください！！
参考はこちら↓
https://github.com/lit-kansai/dj-system-ios/blob/ff89e10bbffd73b8e5b013718681ed00a71bbd53/DJSystemiOS/Pages/RequestMusicPage/RequestMusicViewController.swift#L37-L53

### AlertをViewControllerから表示するようにする

アラートはUIKitのアラートを使い、ViewControllerからひょうじするようにしてください！！(そのほうが処理が複雑にならないと思うので！)

### Routerパターンを使用する

Routerパターンを使って画面遷移周りのロジックを切り出してください！！
Routerパターンの参考はこちら↓
- [iOSにRouterという概念があるらしい。 - Qiita](https://qiita.com/daichi77/items/0ae4946045f99f2643b4)
- iOS設計パターンの本読むのがいいかも
- [Routing with MVVM on iOS. I have been using MVVM for a while in… | by Göksel Köksal | Commencis | Medium](https://medium.com/commencis/routing-with-mvvm-on-ios-f22d021ad2b2)←英語ですまん
- [[iOS] ViewControllerが遷移先のViewControllerについて知っているのが気持ち悪い！ | DevelopersIO](https://dev.classmethod.jp/articles/ios-viewcontroller-knows-viewcontroller-feel-strange/)

### ✅ 作業
- [x] HomePageの名前変更
- [x] APIとの通信周りをAPIClientに書き換える
- [x] Routerパターンを使用する
- [x] AlertをViewControllerから表示するようにする

### 🚀 完了条件
- 作業が全部終わる

**Comment by 9-sho-5** [comment]
- Environmentでエラー出たのでメモしとく
https://stackoverflow.com/questions/57378736/error-class-environment-cannot-be-used-as-an-attribute-received-when-enviro

**Comment by 9-sho-5** [comment]
- SceneDelegateのRouterの設定
```
guard let windowScene = (scene as? UIWindowScene) else { return }

        let window = UIWindow(windowScene: windowScene)
        // MARK: 自分が実装してる画面に書き換えてね
        let rootViewController = SearchRoomPageViewController(roomAPI: Room.API())
        rootViewController.inject(presenter: SearchRoomPresenter(router: SearchRoomRouter(controller: rootViewController)))
        
        let navigationController = UINavigationController(rootViewController: rootViewController)
        window.rootViewController = navigationController
        
        self.window = window
        self.window?.makeKeyAndVisible()
```
